// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs
// https://dbdiagram.io/d

Table pokemon {
  id integer [primary key]
  name string [not null]
  number string [not null]
  gen string [not null]
  type1 string [not null]
  type2 string
  category string [not null]
  height float [not null]
  weight float [not null]
}